# Form implementation generated from reading ui file 'delete.ui'
#
# Created by: PyQt6 UI code generator 6.8.0.dev2410211537
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_delete_form(object):
    def setupUi(self, delete_form):
        delete_form.setObjectName("delete_form")
        delete_form.resize(482, 370)
        self.label = QtWidgets.QLabel(parent=delete_form)
        self.label.setGeometry(QtCore.QRect(20, 20, 451, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(parent=delete_form)
        self.lineEdit.setGeometry(QtCore.QRect(10, 60, 441, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(parent=delete_form)
        self.pushButton.setGeometry(QtCore.QRect(10, 120, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(delete_form)
        QtCore.QMetaObject.connectSlotsByName(delete_form)

    def retranslateUi(self, delete_form):
        _translate = QtCore.QCoreApplication.translate
        delete_form.setWindowTitle(_translate("delete_form", "Form"))
        self.label.setText(_translate("delete_form", "Введите название песни для удаления:"))
        self.pushButton.setText(_translate("delete_form", "Готово!"))
