# Form implementation generated from reading ui file 'genre.ui'
#
# Created by: PyQt6 UI code generator 6.8.0.dev2410211537
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Genre_Form(object):
    def setupUi(self, Genre_Form):
        Genre_Form.setObjectName("Genre_Form")
        Genre_Form.resize(680, 557)
        self.label = QtWidgets.QLabel(parent=Genre_Form)
        self.label.setGeometry(QtCore.QRect(10, 10, 441, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(parent=Genre_Form)
        self.lineEdit.setGeometry(QtCore.QRect(10, 50, 321, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(parent=Genre_Form)
        self.pushButton.setGeometry(QtCore.QRect(10, 100, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.all = QtWidgets.QListWidget(parent=Genre_Form)
        self.all.setGeometry(QtCore.QRect(10, 220, 491, 301))
        self.all.setObjectName("all")
        self.label_2 = QtWidgets.QLabel(parent=Genre_Form)
        self.label_2.setGeometry(QtCore.QRect(20, 170, 481, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Genre_Form)
        QtCore.QMetaObject.connectSlotsByName(Genre_Form)

    def retranslateUi(self, Genre_Form):
        _translate = QtCore.QCoreApplication.translate
        Genre_Form.setWindowTitle(_translate("Genre_Form", "Form"))
        self.label.setText(_translate("Genre_Form", "Введите название жанра:"))
        self.pushButton.setText(_translate("Genre_Form", "Готово!"))
        self.label_2.setText(_translate("Genre_Form", "Список уже доступных жанров:"))
