# Form implementation generated from reading ui file 'song.ui'
#
# Created by: PyQt6 UI code generator 6.8.0.dev2410211537
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Song_Form(object):
    def setupUi(self, Song_Form):
        Song_Form.setObjectName("Song_Form")
        Song_Form.resize(546, 384)
        self.label = QtWidgets.QLabel(parent=Song_Form)
        self.label.setGeometry(QtCore.QRect(10, 20, 501, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(parent=Song_Form)
        self.lineEdit.setGeometry(QtCore.QRect(10, 70, 441, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(parent=Song_Form)
        self.pushButton.setGeometry(QtCore.QRect(10, 200, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(parent=Song_Form)
        self.label_2.setGeometry(QtCore.QRect(10, 120, 251, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Song_Form)
        QtCore.QMetaObject.connectSlotsByName(Song_Form)

    def retranslateUi(self, Song_Form):
        _translate = QtCore.QCoreApplication.translate
        Song_Form.setWindowTitle(_translate("Song_Form", "Form"))
        self.label.setText(_translate("Song_Form", "Введите имя автора, название песни и жанр через запятую:"))
        self.pushButton.setText(_translate("Song_Form", "Готово!"))
        self.label_2.setText(_translate("Song_Form", "Пример: Егор, октябрь, шансон"))
